### ISSUE TITLE
`proposal.metadata` is always blank

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/subgraph-cosmos-proposals#15]
Strange that none of the proposals contain any `metadata` field
https://docs.cosmos.network/v0.47/modules/gov#proposal-3

## GraphQL
```graphql
query{
  proposals(orderBy:block__number, where:{metadata_not:""}) {
    id
    block{
      number
      date
    }
    proposer
    title
    metadata
    summary,
  }
}
```

**Comment by zolting** [comment]
I don't think that's a bug. Metadata field is not included in `MsgSubmitProposalV1Beta1`, so we default to an empty string in that case. For `MsgSuibmitProposalV1`, most proposals decide to just leave an empty string anyway

**Comment by DenisCarriere** [comment]
Ah yes, noticed that too, seems like it's just empty

Just figured it might of been an error, but it's just there's no data
