### ISSUE TITLE
Refactor keys to `snake_case`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/subgraph-cosmos-proposals#18]
I believe it would be best to switch the syntax to `snake_case`

Since all the Protobuf are in `snake_case`, it's slightly annoying having to change to `camelCase` to adjust for GraphQL syntax

When using `camelCase`, you can't copy the key and compare in BufBuild Protobuf definition

For example `subject_client_id` => `subjectClientId`

![image](https://github.com/user-attachments/assets/cbe2f4f4-4932-4b41-b83d-709c8cf925e4)

**Comment by zolting** [comment]
Implementend in commit [#b4896b4c277cabdc98baee44ba085af1a0d2290d](https://github.com/pinax-network/subgraph-cosmos-proposals/commit/b4896b4c277cabdc98baee44ba085af1a0d2290d)
