### ISSUE TITLE
Substreams Store to hold Governance Params

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/subgraph-cosmos-proposals#22]
use Substreams Store to hold pending proposal state changes, apply them when proposal is passed as successful
- [ ] Store all pending proposal changes as JSON String to Substreams Store
- [ ] Whenever a proposal is Successful, read pending changes of that proposal
- [ ] Update new values to `GovernanceParameters`

Ref: https://github.com/pinax-network/subgraph-cosmos-proposals/issues/7

**Comment by zolting** [comment]
Fully implemented in #23
