### ISSUE TITLE
Refactor `Proposal` & `Content` to reuse similar fields

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/subgraph-cosmos-proposals#5]
These entities re-use a lot of the same fields

## Tasks

- [x] refactor `Proposal`
- [x] refactor `Content`
- [x] for `typeUrl`, use `content` instead of hardcoding string (ex: "/cosmos.distribution.v1beta1.MsgCommunityPoolSpend")

```rust
tables
    .create_row("Proposal", &proposal_id)
    .set("txHash", tx_hash)
    .set("block", &clock.id)
    .set("type", "SoftwareUpgrade")
    .set("proposer", proposer)
    .set("authority", authority)
    .set("title", title)
    .set("description", summary)
    .set("metadata", metadata);
```

```rust
tables
  .create_row("Content", &proposal_id)
  .set("proposal", &proposal_id)
  .set("typeUrl", &content.type_url)
  .set("jsonData", data.to_string());
```

<img width="402" alt="image" src="https://github.com/user-attachments/assets/94b061c7-13e6-46b4-a941-558953675948">

<img width="464" alt="image" src="https://github.com/user-attachments/assets/235d3180-ecbe-4c1d-afe3-7307a57d6d20">

**Comment by zolting** [comment]
Completed in commit [b39ca34a274a58b2604221f085cc19b25a1deeeb](https://github.com/pinax-network/subgraph-cosmos-proposals/commit/b39ca34a274a58b2604221f085cc19b25a1deeeb)
