### ISSUE TITLE
Apply Block `retain` based on `event.attribute`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/subgraph-cosmos-proposals#9]
based on the following BlockFilter indexes, apply the same logic to `map_blocks` to filter out by `event.attribute` & `event.type`

```rust
for tx_result in block.tx_results.iter() {
    for event in tx_result.events.iter() {
        keys.insert(format!("type:{}", event.r#type));
        event.attributes.iter().for_each(|attr| {
            keys.insert(format!("attr:{}", attr.key));
        });
    }
}
```

### Available query fields

These are the expressions that can be used in queries:

- `type:<type>` - event type
- `attr:<attribute>` - event attribute

Queries can include `&&` and `||` logical operands, as well as `(` and `)` parenthesis.

**Comment by zolting** [comment]
Implemented in commit [#9c2b074fa315ef0a4e7ad972cfe05f950dcd8e60](https://github.com/pinax-network/subgraph-cosmos-proposals/commit/9c2b074fa315ef0a4e7ad972cfe05f950dcd8e60)
